version: '3.8'
services:
  postgres:
    image: postgres:14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: banking
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  zookeeper:
    image: confluentinc/cp-zookeeper:7.3.1
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.3.1
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    ports:
      - "9092:9092"

  auth-service:
    build: ./auth-service
    environment:
      - DATABASE_URL=postgresql://tby:Tanboyuan0724%29@bank2.postgres.database.azure.com:5432/postgres?sslmode=require
      - JWT_SECRET=my_jwt_secret
    depends_on:
      - postgres
    ports:
      - "4001:4001"

  account-service:
    build: ./account-service
    environment:
      - DATABASE_URL=postgresql://tby:Tanboyuan0724%29@bank2.postgres.database.azure.com:5432/postgres?sslmode=require
      - REDIS_URL=redis://redis:6379
    depends_on:
      - postgres
      - redis
    ports:
      - "4002:4002"

  transaction-service:
    build: ./transaction-service
    environment:
      - DATABASE_URL=postgresql://tby:Tanboyuan0724%29@bank2.postgres.database.azure.com:5432/postgres?sslmode=require
      - KAFKA_BROKER=kafka:9092
    depends_on:
      - postgres
      - kafka
      - account-service
    ports:
      - "4003:4003"

  notification-service:
    build: ./notification-service
    environment:
      - DATABASE_URL=postgresql://tby:Tanboyuan0724%29@bank2.postgres.database.azure.com:5432/postgres?sslmode=require
      - KAFKA_BROKER=kafka:9092
    depends_on:
      - postgres
      - kafka
    ports:
      - "4004:4004"

  file-service:
    build: ./file-service
    environment:
      - DATABASE_URL=postgresql://tby:Tanboyuan0724%29@bank2.postgres.database.azure.com:5432/postgres?sslmode=require
      - AZURE_STORAGE_CONNECTION_STRING=DefaultEndpointsProtocol=https;AccountName=mystorageaccount8777;AccountKey=baCO41DuLu+eEV2bpLRiOqOWXqTjYTlV5LJUAiicZYNN7ZmqeOK+X1ywz8FDSE58iXkWFEw/f5+5+AStcu2r1Q==;EndpointSuffix=core.windows.net
      - AZURE_STORAGE_CONTAINER_NAME=uploads
    depends_on:
      - postgres
    ports:
      - "4005:4005"


volumes:
  pgdata:
