require('dotenv').config();
const express = require('express');
const { createProxyMiddleware } = require('http-proxy-middleware');
const app = express();
app.use(express.json());
const authTarget = `http://auth-service:${process.env.PORT_AUTH}`;
const accountTarget = `http://account-service:${process.env.PORT_ACCOUNT}`;
const transactionTarget = `http://transaction-service:${process.env.PORT_TRANSACTION}`;
const notificationTarget = `http://notification-service:${process.env.PORT_NOTIFICATION}`;
const fileTarget = `http://file-service:${process.env.PORT_FILE}`;
app.use('/auth', createProxyMiddleware({ target: authTarget, changeOrigin: true }));
app.use('/accounts', createProxyMiddleware({ target: accountTarget, changeOrigin: true }));
app.use('/transactions', createProxyMiddleware({ target: transactionTarget, changeOrigin: true }));
app.use('/notifications', createProxyMiddleware({ target: notificationTarget, changeOrigin: true }));
app.use('/files', createProxyMiddleware({ target: fileTarget, changeOrigin: true }));
const port = process.env.PORT_API_GATEWAY || 3000;
app.listen(port, () => { console.log(`API Gateway running on port ${port}`); });
